gpu_id: '0'
log_wandb: False
reproducibility: True

# tim4rec settings
hidden_size: 256                 # (int) Number of features in the hidden state.
num_layers: 2                 # (int) Number of TiSSD layers.
dropout_prob: 0.2            # (float) Dropout rate.
time_drop_out: 0.2
loss_type: 'CE'                 # (str) Type of loss function. Range in ['BPR', 'CE'].

d_state: 64                     # (int) SSD state expansion factor
d_conv: 4                       # (int) Local convolution width
expand: 2                       # (int) Block expansion factor
head_dim: 128                   # (int) Number of SSD heads
chunk_size: 32                 # (int) Size of SSD Chunk
norm_eps: 1e-12

is_ffn: True
is_time: False
p2p_residual: False
is_kai_ming_init: True

# dataset settings
dataset: ml-1m
MAX_ITEM_LIST_LENGTH: 200       # 200 for MovieLens-1M

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
load_col:
    inter: [user_id, item_id, timestamp]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# training settings
epochs: 300
train_batch_size: 512
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 20
train_neg_sample_args: ~
train_from_scratch: False
#checkpoint_path: saved/SSD4Rec-Sep-08-2024_13-01-59.pth

# evaluation settings
metrics: ['Hit', 'NDCG', 'MRR']
valid_metric: NDCG@10
eval_batch_size: 1024

weight_decay: 0.0
topk: [10, 20, 50]