gpu_id: '0'
log_wandb: False

# SASRec settings
hidden_size: 64
inner_size: 256
n_layers: 2
n_heads: 8
hidden_dropout_prob: 0.2
attn_dropout_prob: 0.2
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'                 # (str) Type of loss function. Range in ['BPR', 'CE'].

save_dataset: False

#dataset settings
#dataset: ml-1m
#MAX_ITEM_LIST_LENGTH: 200       # 200 for MovieLens-1M

#dataset: amazon-beauty
#dataset: kuairand
dataset: steam
MAX_ITEM_LIST_LENGTH: 50      # 50 for Amazon datasets

#USER_ID_FIELD: user_id
#ITEM_ID_FIELD: item_id
#load_col:
#    inter: [user_id, item_id, timestamp]

USER_ID_FIELD: user_id
ITEM_ID_FIELD: product_id
load_col:
    inter: [user_id, product_id, timestamp]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# training settings
epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10
train_neg_sample_args: ~
train_from_scratch: False

# evaluation settings
metrics: ['Hit', 'NDCG', 'MRR']
valid_metric: NDCG@10
eval_batch_size: 4096
weight_decay: 0.0
topk: [10, 20, 50]
